### DELETING OLD OPENSHIFT FILE
- name: Deleting old hosts file
  file:
     path: "./tmp/openshift.config"
     state: absent
  ignore_errors: True
  tags: 
     - openshift_inventory

### CREATING OPENSHIFT CONFIG FILE
- name: Copying Openshift file template
  copy:
     src="./templates/openshift_hosts.j2"
     dest="./tmp/openshift.config"
  tags:
     - openshift_inventory

###  ADDING VARIABLES
- name: Adding subdomain info
  lineinfile: 
           line: "openshift_master_default_subdomain={{ openshift_subdomain }}"
           path: "./tmp/openshift.config"
  tags:
     - openshift_inventory

- name: Adding registry replicas
  lineinfile: 
           line: "openshift_hosted_registry_replicas={{ infra_nodes }}"
           path: "./tmp/openshift.config"
  tags:
     - openshift_inventory

- name: Adding router replicas
  lineinfile: 
           line: "openshift_hosted_router_replicas={{ infra_nodes }}"
           path: "./tmp/openshift.config"
  tags:
     - openshift_inventory


###" CREATING MASTERS DEFINITION
- name: Adding masters header
  lineinfile: 
           line: "\n[masters]"
           path: "./tmp/openshift.config"
  tags:
     - openshift_inventory

- name: Adding masters to masters group
  lineinfile: 
           line: "{{ prefix_id }}-master{{ item }} node=True storage=True master=True"
           path: "./tmp/openshift.config"
  with_sequence: "count={{ master_nodes }}"
  tags:
     - openshift_inventory

 ### CREATING NODES DEFINITION    
- name: Adding nodes header
  lineinfile: 
           line: "\n[nodes]"
           path: "./tmp/openshift.config"
  tags:
     - openshift_inventory

- name: Adding masters to nodes to group
  lineinfile: 
           line: "{{ prefix_id }}-master{{ item }} node=True storage=True master=True openshift_schedulable=False"
           path: "./tmp/openshift.config"
  with_sequence: "count={{ master_nodes }}"
  tags:
     - openshift_inventory

- name: Adding infra to nodes to group
  lineinfile: 
           line: "{{ prefix_id }}-infra{{ item }}  openshift_node_labels=\"{\'host\': \'infra\'}\" node=True openshift_schedulable=True"
           path: "./tmp/openshift.config"
  with_sequence: "count={{ infra_nodes }}"
  tags:
     - openshift_inventory

- name: Adding nodes to nodes to group
  lineinfile: 
           line: "{{ prefix_id }}-node{{ item }}  openshift_node_labels=\"{\'host\': \'apps\'}\" node=True openshift_schedulable=True"
           path: "./tmp/openshift.config"
  with_sequence: "count={{ process_nodes }}"
  tags:
     - openshift_inventory

- name: Adding gluster to nodes to group
  lineinfile: 
           line: "{{ prefix_id }}-gluster{{ item }}  openshift_node_labels=\"{\'host\': \'apps\'}\" node=True openshift_schedulable=True"
           path: "./tmp/openshift.config"
  with_sequence: "count={{ gluster_nodes }}"
  tags:
     - openshift_inventory


###' CREATING ETCD DEFINITION
- name: Adding nodes header
  lineinfile: 
           line: "\n[etcd]"
           path: "./tmp/openshift.config"
  tags:
     - openshift_inventory

- name: Adding masters to etcd group
  lineinfile: 
           line: "{{ prefix_id }}-master{{ item }} node=True storage=True master=True "
           path: "./tmp/openshift.config"
  with_sequence: "count={{ master_nodes }}"
  tags:
     - openshift_inventory

### CREATING GLUSTERFS DEFINITION   
- name: Adding nodes header
  lineinfile: 
           line: "\n[glusterfs]"
           path: "./tmp/openshift.config"
  tags:
     - openshift_inventory

- name: Adding gluster nodes to glusterfs group
  lineinfile: 
           line: "{{ prefix_id }}-gluster{{ item }}  glusterfs_devices=\'[\"/dev/sdc\"]\'"
           path: "./tmp/openshift.config"
  with_sequence: "count={{ gluster_nodes }}"
  tags:
     - openshift_inventory

### CREATING GLUSTERFS_REGISTRY DEFINITION   
- name: Adding nodes header
  lineinfile: 
           line: "\n[glusterfs_registry]"
           path: "./tmp/openshift.config"
  tags:
     - openshift_inventory

- name: Adding gluster nodes to glusterfs group
  lineinfile: 
           line: "{{ prefix_id }}-infra{{ item }}  glusterfs_devices=\'[\"/dev/sdc\"]\'"
           path: "./tmp/openshift.config"
  with_sequence: "count={{ infra_nodes }}"
  tags:
     - openshift_inventory


### CREATING LOADBALANCER DEFINITION   
- name: Adding masters balancer header
  lineinfile: 
           line: "\n[lb]"
           path: "./tmp/openshift.config"
  tags:
     - openshift_inventory

- name: Adding load balancer hosts to lb group
  lineinfile: 
           line: "{{ prefix_id }}-mlb{{ item }}"
           path: "./tmp/openshift.config"
  with_sequence: "count={{ masters_balancers }}"
  tags:
     - openshift_inventory
