---
- name: Selecting main installation server for 3 scale
  hosts: localhost
  gather_facts: False
  vars_files:
     - settings/authentications
     - settings/defaults
  tasks:
      - name: Retriving Installer host
        set_fact: headnodes={{ groups[['openshift_master_group'][0]] }}
        tags:
           - selecting_headnode

      - name: Selecting first master as main installer
        add_host: groups=openshift_headnode_group hostname={{ headnodes[0] }}
                  ansible_user={{ ssh_default_image_user }} ansible_password={{ ssh_default_image_password }}
                  ansible_port={{ ssh_default_image_port }}
        tags:
           - selecting_headnode

- name: Install 3 Scale
  hosts: openshift_headnode_group
  gather_facts: False
  vars_files:
     - settings/authentications
     - settings/defaults
  tasks:
      - name: Copying amq.j2 template
        copy:
           src="./templates/amp.j2"
           dest="/root/amp.yaml"
        ignore_errors: True
        tags:
           - 3scale

      - name: Deleting 3scale Environment If exists
        command: "oc delete project 3scale"
        ignore_errors: True
        tags:
           - 3scale

      - name: Deleting 3scale secrets if exists
        command: "oc delete secret apicast-configuration-url-secret"
        ignore_errors: True
        tags:
           - 3scale

      - name: Waiting for 3 scale project to end...
        pause:
            minutes: 1
        tags:
           - install_openshift

      - name: Creating 3scale Environment
        command: "oc new-project 3scale --display-name=\"3 Scale\""
        ignore_errors: True
        tags:
           - 3scale

      - name: Adding DV user to 3scale
        command: "oadm policy add-role-to-user admin dv -n 3scale"
        tags:
           - 3scale

      - name: Adding 3 scale secret token
        command: "oc secret new-basicauth apicast-configuration-url-secret --password=https://4582fed8a3e30d3f7a196c43c051ad98de89d939f808a5bd7da9828b646a383d@cloudapps-admin.3scale.net"
        tags:
           - 3scale

      - name: Running Yaml File
        command: "oc new-app -f https://raw.githubusercontent.com/3scale/3scale-amp-openshift-templates/2.0.0.GA-redhat-2/apicast-gateway/apicast.yml -n 3scale"
        tags:
           - 3scale
